#
# Created for the Northwind_new DATABASE
#
 
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;

USE `northwind_new`;


#
# Dumping data for table 'customers'
#

INSERT INTO `customers` (`id`, `company`, `last_name`, `first_name`, `email_address`, `job_title`, `business_phone`, `home_phone`, `mobile_phone`, `fax_number`, `address`, `city`, `state_province`, `zip_postal_code`, `country_region`, `web_page`, `notes`, `attachments`) VALUES (1, 'Company A', 'Bedecs', 'Anna', NULL, 'Owner', '(123)555-0100', NULL, NULL, '(123)555-0101', '123 1st Street', 'Seattle', 'WA', '99999', 'USA', NULL, NULL, '');
INSERT INTO `customers` (`id`, `company`, `last_name`, `first_name`, `email_address`, `job_title`, `business_phone`, `home_phone`, `mobile_phone`, `fax_number`, `address`, `city`, `state_province`, `zip_postal_code`, `country_region`, `web_page`, `notes`, `attachments`) VALUES (2, 'Company B', 'Gratacos Solsona', 'Antonio', NULL, 'Owner', '(123)555-0100', NULL, NULL, '(123)555-0101', '123 2nd Street', 'Boston', 'MA', '99999', 'USA', NULL, NULL, '');
INSERT INTO `customers` (`id`, `company`, `last_name`, `first_name`, `email_address`, `job_title`, `business_phone`, `home_phone`, `mobile_phone`, `fax_number`, `address`, `city`, `state_province`, `zip_postal_code`, `country_region`, `web_page`, `notes`, `attachments`) VALUES (3, 'Company C', 'Axen', 'Thomas', NULL, 'Purchasing Representative', '(123)555-0100', NULL, NULL, '(123)555-0101', '123 3rd Street', 'Los Angelas', 'CA', '99999', 'USA', NULL, NULL, '');
INSERT INTO `customers` (`id`, `company`, `last_name`, `first_name`, `email_address`, `job_title`, `business_phone`, `home_phone`, `mobile_phone`, `fax_number`, `address`, `city`, `state_province`, `zip_postal_code`, `country_region`, `web_page`, `notes`, `attachments`) VALUES (4, 'Company D', 'Lee', 'Christina', NULL, 'Purchasing Manager', '(123)555-0100', NULL, NULL, '(123)555-0101', '123 4th Street', 'New York', 'NY', '99999', 'USA', NULL, NULL, '');
INSERT INTO `customers` (`id`, `company`, `last_name`, `first_name`, `email_address`, `job_title`, `business_phone`, `home_phone`, `mobile_phone`, `fax_number`, `address`, `city`, `state_province`, `zip_postal_code`, `country_region`, `web_page`, `notes`, `attachments`) VALUES (5, 'Company E', 'O’Donnell', 'Martin', NULL, 'Owner', '(123)555-0100', NULL, NULL, '(123)555-0101', '123 5th Street', 'Minneapolis', 'MN', '99999', 'USA', NULL, NULL, '');
INSERT INTO `customers` (`id`, `company`, `last_name`, `first_name`, `email_address`, `job_title`, `business_phone`, `home_phone`, `mobile_phone`, `fax_number`, `address`, `city`, `state_province`, `zip_postal_code`, `country_region`, `web_page`, `notes`, `attachments`) VALUES (6, 'Company F', 'Pérez-Olaeta', 'Francisco', NULL, 'Purchasing Manager', '(123)555-0100', NULL, NULL, '(123)555-0101', '123 6th Street', 'Milwaukee', 'WI', '99999', 'USA', NULL, NULL, '');
INSERT INTO `customers` (`id`, `company`, `last_name`, `first_name`, `email_address`, `job_title`, `business_phone`, `home_phone`, `mobile_phone`, `fax_number`, `address`, `city`, `state_province`, `zip_postal_code`, `country_region`, `web_page`, `notes`, `attachments`) VALUES (7, 'Company G', 'Xie', 'Ming-Yang', NULL, 'Owner', '(123)555-0100', NULL, NULL, '(123)555-0101', '123 7th Street', 'Boise', 'ID', '99999', 'USA', NULL, NULL, '');
INSERT INTO `customers` (`id`, `company`, `last_name`, `first_name`, `email_address`, `job_title`, `business_phone`, `home_phone`, `mobile_phone`, `fax_number`, `address`, `city`, `state_province`, `zip_postal_code`, `country_region`, `web_page`, `notes`, `attachments`) VALUES (8, 'Company H', 'Andersen', 'Elizabeth', NULL, 'Purchasing Representative', '(123)555-0100', NULL, NULL, '(123)555-0101', '123 8th Street', 'Portland', 'OR', '99999', 'USA', NULL, NULL, '');
INSERT INTO `customers` (`id`, `company`, `last_name`, `first_name`, `email_address`, `job_title`, `business_phone`, `home_phone`, `mobile_phone`, `fax_number`, `address`, `city`, `state_province`, `zip_postal_code`, `country_region`, `web_page`, `notes`, `attachments`) VALUES (9, 'Company I', 'Mortensen', 'Sven', NULL, 'Purchasing Manager', '(123)555-0100', NULL, NULL, '(123)555-0101', '123 9th Street', 'Salt Lake City', 'UT', '99999', 'USA', NULL, NULL, '');
INSERT INTO `customers` (`id`, `company`, `last_name`, `first_name`, `email_address`, `job_title`, `business_phone`, `home_phone`, `mobile_phone`, `fax_number`, `address`, `city`, `state_province`, `zip_postal_code`, `country_region`, `web_page`, `notes`, `attachments`) VALUES (10, 'Company J', 'Wacker', 'Roland', NULL, 'Purchasing Manager', '(123)555-0100', NULL, NULL, '(123)555-0101', '123 10th Street', 'Chicago', 'IL', '99999', 'USA', NULL, NULL, '');
INSERT INTO `customers` (`id`, `company`, `last_name`, `first_name`, `email_address`, `job_title`, `business_phone`, `home_phone`, `mobile_phone`, `fax_number`, `address`, `city`, `state_province`, `zip_postal_code`, `country_region`, `web_page`, `notes`, `attachments`) VALUES (11, 'Company K', 'Krschne', 'Peter', NULL, 'Purchasing Manager', '(123)555-0100', NULL, NULL, '(123)555-0101', '123 11th Street', 'Miami', 'FL', '99999', 'USA', NULL, NULL, '');
INSERT INTO `customers` (`id`, `company`, `last_name`, `first_name`, `email_address`, `job_title`, `business_phone`, `home_phone`, `mobile_phone`, `fax_number`, `address`, `city`, `state_province`, `zip_postal_code`, `country_region`, `web_page`, `notes`, `attachments`) VALUES (12, 'Company L', 'Edwards', 'John', NULL, 'Purchasing Manager', '(123)555-0100', NULL, NULL, '(123)555-0101', '123 12th Street', 'Las Vegas', 'NV', '99999', 'USA', NULL, NULL, '');
INSERT INTO `customers` (`id`, `company`, `last_name`, `first_name`, `email_address`, `job_title`, `business_phone`, `home_phone`, `mobile_phone`, `fax_number`, `address`, `city`, `state_province`, `zip_postal_code`, `country_region`, `web_page`, `notes`, `attachments`) VALUES (13, 'Company M', 'Ludick', 'Andre', NULL, 'Purchasing Representative', '(123)555-0100', NULL, NULL, '(123)555-0101', '456 13th Street', 'Memphis', 'TN', '99999', 'USA', NULL, NULL, '');
INSERT INTO `customers` (`id`, `company`, `last_name`, `first_name`, `email_address`, `job_title`, `business_phone`, `home_phone`, `mobile_phone`, `fax_number`, `address`, `city`, `state_province`, `zip_postal_code`, `country_region`, `web_page`, `notes`, `attachments`) VALUES (14, 'Company N', 'Grilo', 'Carlos', NULL, 'Purchasing Representative', '(123)555-0100', NULL, NULL, '(123)555-0101', '456 14th Street', 'Denver', 'CO', '99999', 'USA', NULL, NULL, '');
INSERT INTO `customers` (`id`, `company`, `last_name`, `first_name`, `email_address`, `job_title`, `business_phone`, `home_phone`, `mobile_phone`, `fax_number`, `address`, `city`, `state_province`, `zip_postal_code`, `country_region`, `web_page`, `notes`, `attachments`) VALUES (15, 'Company O', 'Kupkova', 'Helena', NULL, 'Purchasing Manager', '(123)555-0100', NULL, NULL, '(123)555-0101', '456 15th Street', 'Honolulu', 'HI', '99999', 'USA', NULL, NULL, '');
INSERT INTO `customers` (`id`, `company`, `last_name`, `first_name`, `email_address`, `job_title`, `business_phone`, `home_phone`, `mobile_phone`, `fax_number`, `address`, `city`, `state_province`, `zip_postal_code`, `country_region`, `web_page`, `notes`, `attachments`) VALUES (16, 'Company P', 'Goldschmidt', 'Daniel', NULL, 'Purchasing Representative', '(123)555-0100', NULL, NULL, '(123)555-0101', '456 16th Street', 'San Francisco', 'CA', '99999', 'USA', NULL, NULL, '');
INSERT INTO `customers` (`id`, `company`, `last_name`, `first_name`, `email_address`, `job_title`, `business_phone`, `home_phone`, `mobile_phone`, `fax_number`, `address`, `city`, `state_province`, `zip_postal_code`, `country_region`, `web_page`, `notes`, `attachments`) VALUES (17, 'Company Q', 'Bagel', 'Jean Philippe', NULL, 'Owner', '(123)555-0100', NULL, NULL, '(123)555-0101', '456 17th Street', 'Seattle', 'WA', '99999', 'USA', NULL, NULL, '');
INSERT INTO `customers` (`id`, `company`, `last_name`, `first_name`, `email_address`, `job_title`, `business_phone`, `home_phone`, `mobile_phone`, `fax_number`, `address`, `city`, `state_province`, `zip_postal_code`, `country_region`, `web_page`, `notes`, `attachments`) VALUES (18, 'Company R', 'Autier Miconi', 'Catherine', NULL, 'Purchasing Representative', '(123)555-0100', NULL, NULL, '(123)555-0101', '456 18th Street', 'Boston', 'MA', '99999', 'USA', NULL, NULL, '');
INSERT INTO `customers` (`id`, `company`, `last_name`, `first_name`, `email_address`, `job_title`, `business_phone`, `home_phone`, `mobile_phone`, `fax_number`, `address`, `city`, `state_province`, `zip_postal_code`, `country_region`, `web_page`, `notes`, `attachments`) VALUES (19, 'Company S', 'Eggerer', 'Alexander', NULL, 'Accounting Assistant', '(123)555-0100', NULL, NULL, '(123)555-0101', '789 19th Street', 'Los Angelas', 'CA', '99999', 'USA', NULL, NULL, '');
INSERT INTO `customers` (`id`, `company`, `last_name`, `first_name`, `email_address`, `job_title`, `business_phone`, `home_phone`, `mobile_phone`, `fax_number`, `address`, `city`, `state_province`, `zip_postal_code`, `country_region`, `web_page`, `notes`, `attachments`) VALUES (20, 'Company T', 'Li', 'George', NULL, 'Purchasing Manager', '(123)555-0100', NULL, NULL, '(123)555-0101', '789 20th Street', 'New York', 'NY', '99999', 'USA', NULL, NULL, '');
INSERT INTO `customers` (`id`, `company`, `last_name`, `first_name`, `email_address`, `job_title`, `business_phone`, `home_phone`, `mobile_phone`, `fax_number`, `address`, `city`, `state_province`, `zip_postal_code`, `country_region`, `web_page`, `notes`, `attachments`) VALUES (21, 'Company U', 'Tham', 'Bernard', NULL, 'Accounting Manager', '(123)555-0100', NULL, NULL, '(123)555-0101', '789 21th Street', 'Minneapolis', 'MN', '99999', 'USA', NULL, NULL, '');
INSERT INTO `customers` (`id`, `company`, `last_name`, `first_name`, `email_address`, `job_title`, `business_phone`, `home_phone`, `mobile_phone`, `fax_number`, `address`, `city`, `state_province`, `zip_postal_code`, `country_region`, `web_page`, `notes`, `attachments`) VALUES (22, 'Company V', 'Ramos', 'Luciana', NULL, 'Purchasing Assistant', '(123)555-0100', NULL, NULL, '(123)555-0101', '789 22th Street', 'Milwaukee', 'WI', '99999', 'USA', NULL, NULL, '');
INSERT INTO `customers` (`id`, `company`, `last_name`, `first_name`, `email_address`, `job_title`, `business_phone`, `home_phone`, `mobile_phone`, `fax_number`, `address`, `city`, `state_province`, `zip_postal_code`, `country_region`, `web_page`, `notes`, `attachments`) VALUES (23, 'Company W', 'Entin', 'Michael', NULL, 'Purchasing Manager', '(123)555-0100', NULL, NULL, '(123)555-0101', '789 23th Street', 'Portland', 'OR', '99999', 'USA', NULL, NULL, '');
INSERT INTO `customers` (`id`, `company`, `last_name`, `first_name`, `email_address`, `job_title`, `business_phone`, `home_phone`, `mobile_phone`, `fax_number`, `address`, `city`, `state_province`, `zip_postal_code`, `country_region`, `web_page`, `notes`, `attachments`) VALUES (24, 'Company X', 'Hasselberg', 'Jonas', NULL, 'Owner', '(123)555-0100', NULL, NULL, '(123)555-0101', '789 24th Street', 'Salt Lake City', 'UT', '99999', 'USA', NULL, NULL, '');
INSERT INTO `customers` (`id`, `company`, `last_name`, `first_name`, `email_address`, `job_title`, `business_phone`, `home_phone`, `mobile_phone`, `fax_number`, `address`, `city`, `state_province`, `zip_postal_code`, `country_region`, `web_page`, `notes`, `attachments`) VALUES (25, 'Company Y', 'Rodman', 'John', NULL, 'Purchasing Manager', '(123)555-0100', NULL, NULL, '(123)555-0101', '789 25th Street', 'Chicago', 'IL', '99999', 'USA', NULL, NULL, '');
INSERT INTO `customers` (`id`, `company`, `last_name`, `first_name`, `email_address`, `job_title`, `business_phone`, `home_phone`, `mobile_phone`, `fax_number`, `address`, `city`, `state_province`, `zip_postal_code`, `country_region`, `web_page`, `notes`, `attachments`) VALUES (26, 'Company Z', 'Liu', 'Run', NULL, 'Accounting Assistant', '(123)555-0100', NULL, NULL, '(123)555-0101', '789 26th Street', 'Miami', 'FL', '99999', 'USA', NULL, NULL, '');
INSERT INTO `customers` (`id`, `company`, `last_name`, `first_name`, `email_address`, `job_title`, `business_phone`, `home_phone`, `mobile_phone`, `fax_number`, `address`, `city`, `state_province`, `zip_postal_code`, `country_region`, `web_page`, `notes`, `attachments`) VALUES (27, 'Company AA', 'Toh', 'Karen', NULL, 'Purchasing Manager', '(123)555-0100', NULL, NULL, '(123)555-0101', '789 27th Street', 'Las Vegas', 'NV', '99999', 'USA', NULL, NULL, '');
INSERT INTO `customers` (`id`, `company`, `last_name`, `first_name`, `email_address`, `job_title`, `business_phone`, `home_phone`, `mobile_phone`, `fax_number`, `address`, `city`, `state_province`, `zip_postal_code`, `country_region`, `web_page`, `notes`, `attachments`) VALUES (28, 'Company BB', 'Raghav', 'Amritansh', NULL, 'Purchasing Manager', '(123)555-0100', NULL, NULL, '(123)555-0101', '789 28th Street', 'Memphis', 'TN', '99999', 'USA', NULL, NULL, '');
INSERT INTO `customers` (`id`, `company`, `last_name`, `first_name`, `email_address`, `job_title`, `business_phone`, `home_phone`, `mobile_phone`, `fax_number`, `address`, `city`, `state_province`, `zip_postal_code`, `country_region`, `web_page`, `notes`, `attachments`) VALUES (29, 'Company CC', 'Lee', 'Soo Jung', NULL, 'Purchasing Manager', '(123)555-0100', NULL, NULL, '(123)555-0101', '789 29th Street', 'Denver', 'CO', '99999', 'USA', NULL, NULL, '');
# 29 records

#
# Dumping data for table 'employees'
#

INSERT INTO `employees` (`id`, `company`, `last_name`, `first_name`, `email_address`, `job_title`, `business_phone`, `home_phone`, `mobile_phone`, `fax_number`, `address`, `city`, `state_province`, `zip_postal_code`, `country_region`, `web_page`, `notes`, `attachments`, `privilege_name`) VALUES (1, 'Northwind Traders', 'Freehafer', 'Nancy', 'nancy@northwindtraders.com', 'Sales Representative', '(123)555-0100', '(123)555-0102', NULL, '(123)555-0103', '123 1st Avenue', 'Seattle', 'WA', '99999', 'USA', '#http://northwindtraders.com#', NULL, '', '');
INSERT INTO `employees` (`id`, `company`, `last_name`, `first_name`, `email_address`, `job_title`, `business_phone`, `home_phone`, `mobile_phone`, `fax_number`, `address`, `city`, `state_province`, `zip_postal_code`, `country_region`, `web_page`, `notes`, `attachments`, `privilege_name`) VALUES (2, 'Northwind Traders', 'Cencini', 'Andrew', 'andrew@northwindtraders.com', 'Vice President, Sales', '(123)555-0100', '(123)555-0102', NULL, '(123)555-0103', '123 2nd Avenue', 'Bellevue', 'WA', '99999', 'USA', 'http://northwindtraders.com#http://northwindtraders.com/#', 'Joined the company as a sales representative, was promoted to sales manager and was then named vice president of sales.', '', 'Purchase Approvals');
INSERT INTO `employees` (`id`, `company`, `last_name`, `first_name`, `email_address`, `job_title`, `business_phone`, `home_phone`, `mobile_phone`, `fax_number`, `address`, `city`, `state_province`, `zip_postal_code`, `country_region`, `web_page`, `notes`, `attachments`, `privilege_name`) VALUES (3, 'Northwind Traders', 'Kotas', 'Jan', 'jan@northwindtraders.com', 'Sales Representative', '(123)555-0100', '(123)555-0102', NULL, '(123)555-0103', '123 3rd Avenue', 'Redmond', 'WA', '99999', 'USA', 'http://northwindtraders.com#http://northwindtraders.com/#', 'Was hired as a sales associate and was promoted to sales representative.', '', '');
INSERT INTO `employees` (`id`, `company`, `last_name`, `first_name`, `email_address`, `job_title`, `business_phone`, `home_phone`, `mobile_phone`, `fax_number`, `address`, `city`, `state_province`, `zip_postal_code`, `country_region`, `web_page`, `notes`, `attachments`, `privilege_name`) VALUES (4, 'Northwind Traders', 'Sergienko', 'Mariya', 'mariya@northwindtraders.com', 'Sales Representative', '(123)555-0100', '(123)555-0102', NULL, '(123)555-0103', '123 4th Avenue', 'Kirkland', 'WA', '99999', 'USA', 'http://northwindtraders.com#http://northwindtraders.com/#', NULL, '', '');
INSERT INTO `employees` (`id`, `company`, `last_name`, `first_name`, `email_address`, `job_title`, `business_phone`, `home_phone`, `mobile_phone`, `fax_number`, `address`, `city`, `state_province`, `zip_postal_code`, `country_region`, `web_page`, `notes`, `attachments`, `privilege_name`) VALUES (5, 'Northwind Traders', 'Thorpe', 'Steven', 'steven@northwindtraders.com', 'Sales Manager', '(123)555-0100', '(123)555-0102', NULL, '(123)555-0103', '123 5th Avenue', 'Seattle', 'WA', '99999', 'USA', 'http://northwindtraders.com#http://northwindtraders.com/#', 'Joined the company as a sales representative and was promoted to sales manager.  Fluent in French.', '', '');
INSERT INTO `employees` (`id`, `company`, `last_name`, `first_name`, `email_address`, `job_title`, `business_phone`, `home_phone`, `mobile_phone`, `fax_number`, `address`, `city`, `state_province`, `zip_postal_code`, `country_region`, `web_page`, `notes`, `attachments`, `privilege_name`) VALUES (6, 'Northwind Traders', 'Neipper', 'Michael', 'michael@northwindtraders.com', 'Sales Representative', '(123)555-0100', '(123)555-0102', NULL, '(123)555-0103', '123 6th Avenue', 'Redmond', 'WA', '99999', 'USA', 'http://northwindtraders.com#http://northwindtraders.com/#', 'Fluent in Japanese and can read and write French, Portuguese, and Spanish.', '', '');
INSERT INTO `employees` (`id`, `company`, `last_name`, `first_name`, `email_address`, `job_title`, `business_phone`, `home_phone`, `mobile_phone`, `fax_number`, `address`, `city`, `state_province`, `zip_postal_code`, `country_region`, `web_page`, `notes`, `attachments`, `privilege_name`) VALUES (7, 'Northwind Traders', 'Zare', 'Robert', 'robert@northwindtraders.com', 'Sales Representative', '(123)555-0100', '(123)555-0102', NULL, '(123)555-0103', '123 7th Avenue', 'Seattle', 'WA', '99999', 'USA', 'http://northwindtraders.com#http://northwindtraders.com/#', NULL, '', '');
INSERT INTO `employees` (`id`, `company`, `last_name`, `first_name`, `email_address`, `job_title`, `business_phone`, `home_phone`, `mobile_phone`, `fax_number`, `address`, `city`, `state_province`, `zip_postal_code`, `country_region`, `web_page`, `notes`, `attachments`, `privilege_name`) VALUES (8, 'Northwind Traders', 'Giussani', 'Laura', 'laura@northwindtraders.com', 'Sales Coordinator', '(123)555-0100', '(123)555-0102', NULL, '(123)555-0103', '123 8th Avenue', 'Redmond', 'WA', '99999', 'USA', 'http://northwindtraders.com#http://northwindtraders.com/#', 'Reads and writes French.', '', '');
INSERT INTO `employees` (`id`, `company`, `last_name`, `first_name`, `email_address`, `job_title`, `business_phone`, `home_phone`, `mobile_phone`, `fax_number`, `address`, `city`, `state_province`, `zip_postal_code`, `country_region`, `web_page`, `notes`, `attachments`, `privilege_name`) VALUES (9, 'Northwind Traders', 'Hellung-Larsen', 'Anne', 'anne@northwindtraders.com', 'Sales Representative', '(123)555-0100', '(123)555-0102', NULL, '(123)555-0103', '123 9th Avenue', 'Seattle', 'WA', '99999', 'USA', 'http://northwindtraders.com#http://northwindtraders.com/#', 'Fluent in French and German.', '', '');
# 9 records

#
# Dumping data for table 'shippers'
#

INSERT INTO `shippers` (`id`, `company`, `last_name`, `first_name`, `email_address`, `job_title`, `business_phone`, `home_phone`, `mobile_phone`, `fax_number`, `address`, `city`, `state_province`, `zip_postal_code`, `country_region`, `web_page`, `notes`, `attachments`) VALUES (1, 'Shipping Company A', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '123 Any Street', 'Memphis', 'TN', '99999', 'USA', NULL, NULL, '');
INSERT INTO `shippers` (`id`, `company`, `last_name`, `first_name`, `email_address`, `job_title`, `business_phone`, `home_phone`, `mobile_phone`, `fax_number`, `address`, `city`, `state_province`, `zip_postal_code`, `country_region`, `web_page`, `notes`, `attachments`) VALUES (2, 'Shipping Company B', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '123 Any Street', 'Memphis', 'TN', '99999', 'USA', NULL, NULL, '');
INSERT INTO `shippers` (`id`, `company`, `last_name`, `first_name`, `email_address`, `job_title`, `business_phone`, `home_phone`, `mobile_phone`, `fax_number`, `address`, `city`, `state_province`, `zip_postal_code`, `country_region`, `web_page`, `notes`, `attachments`) VALUES (3, 'Shipping Company C', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '123 Any Street', 'Memphis', 'TN', '99999', 'USA', NULL, NULL, '');
# 3 records

#
# Dumping data for table 'order_details'
#
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('91', '81', '56', '0.0000', '38.0000', '0', 'None', 'NWTP-56', 'Northwind Traders Gnocchi', '28.5000', '38.0000', '0', 'Pasta');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('42', '41', '43', '300.0000', '46.0000', '0', 'Allocated', 'NWTB-43', 'Northwind Traders Coffee', '34.5000', '46.0000', '0', 'Beverages');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('46', '43', '80', '20.0000', '3.5000', '0', 'Allocated', 'NWTDFN-80', 'Northwind Traders Dried Plums', '3.0000', '3.5000', '0', 'Dried Fruit & Nuts');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('47', '43', '81', '50.0000', '2.9900', '0', 'Allocated', 'NWTB-81', 'Northwind Traders Green Tea', '2.0000', '2.9900', '0', 'Beverages');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('48', '44', '1', '25.0000', '18.0000', '0', 'Allocated', 'NWTB-1', 'Northwind Traders Chai', '13.5000', '18.0000', '0', 'Beverages');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('49', '44', '43', '25.0000', '46.0000', '0', 'Allocated', 'NWTB-43', 'Northwind Traders Coffee', '34.5000', '46.0000', '0', 'Beverages');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('50', '44', '81', '25.0000', '2.9900', '0', 'Allocated', 'NWTB-81', 'Northwind Traders Green Tea', '2.0000', '2.9900', '0', 'Beverages');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('86', '80', '56', '10.0000', '38.0000', '0', 'Allocated', 'NWTP-56', 'Northwind Traders Gnocchi', '28.5000', '38.0000', '0', 'Pasta');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('27', '30', '34', '100.0000', '14.0000', '0', 'Invoiced', 'NWTB-34', 'Northwind Traders Beer', '10.5000', '14.0000', '0', 'Beverages');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('28', '30', '80', '30.0000', '3.5000', '0', 'Invoiced', 'NWTDFN-80', 'Northwind Traders Dried Plums', '3.0000', '3.5000', '0', 'Dried Fruit & Nuts');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('29', '31', '7', '10.0000', '30.0000', '0', 'Invoiced', 'NWTDFN-7', 'Northwind Traders Dried Pears', '22.5000', '30.0000', '0', 'Dried Fruit & Nuts');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('30', '31', '51', '10.0000', '53.0000', '0', 'Invoiced', 'NWTDFN-51', 'Northwind Traders Dried Apples', '39.7500', '53.0000', '0', 'Dried Fruit & Nuts');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('31', '31', '80', '10.0000', '3.5000', '0', 'Invoiced', 'NWTDFN-80', 'Northwind Traders Dried Plums', '3.0000', '3.5000', '0', 'Dried Fruit & Nuts');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('32', '32', '1', '15.0000', '18.0000', '0', 'Invoiced', 'NWTB-1', 'Northwind Traders Chai', '13.5000', '18.0000', '0', 'Beverages');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('33', '32', '43', '20.0000', '46.0000', '0', 'Invoiced', 'NWTB-43', 'Northwind Traders Coffee', '34.5000', '46.0000', '0', 'Beverages');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('34', '33', '19', '30.0000', '9.2000', '0', 'Invoiced', 'NWTBGM-19', 'Northwind Traders Chocolate Biscuits Mix', '6.9000', '9.2000', '0', 'Baked Goods & Mixes');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('35', '34', '19', '20.0000', '9.2000', '0', 'Invoiced', 'NWTBGM-19', 'Northwind Traders Chocolate Biscuits Mix', '6.9000', '9.2000', '0', 'Baked Goods & Mixes');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('36', '35', '48', '10.0000', '12.7500', '0', 'Invoiced', 'NWTCA-48', 'Northwind Traders Chocolate', '9.5625', '12.7500', '0', 'Candy');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('37', '36', '41', '200.0000', '9.6500', '0', 'Invoiced', 'NWTSO-41', 'Northwind Traders Clam Chowder', '7.2375', '9.6500', '0', 'Soups');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('38', '37', '8', '17.0000', '40.0000', '0', 'Invoiced', 'NWTS-8', 'Northwind Traders Curry Sauce', '30.0000', '40.0000', '0', 'Sauces');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('39', '38', '43', '300.0000', '46.0000', '0', 'Invoiced', 'NWTB-43', 'Northwind Traders Coffee', '34.5000', '46.0000', '0', 'Beverages');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('40', '39', '48', '100.0000', '12.7500', '0', 'Invoiced', 'NWTCA-48', 'Northwind Traders Chocolate', '9.5625', '12.7500', '0', 'Candy');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('41', '40', '81', '200.0000', '2.9900', '0', 'Invoiced', 'NWTB-81', 'Northwind Traders Green Tea', '2.0000', '2.9900', '0', 'Beverages');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('43', '42', '6', '10.0000', '25.0000', '0', 'Invoiced', 'NWTJP-6', 'Northwind Traders Boysenberry Spread', '18.7500', '25.0000', '0', 'Jams, Preserves');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('44', '42', '4', '10.0000', '22.0000', '0', 'Invoiced', 'NWTCO-4', 'Northwind Traders Cajun Seasoning', '16.5000', '22.0000', '0', 'Condiments');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('45', '42', '19', '10.0000', '9.2000', '0', 'Invoiced', 'NWTBGM-19', 'Northwind Traders Chocolate Biscuits Mix', '6.9000', '9.2000', '0', 'Baked Goods & Mixes');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('51', '45', '41', '50.0000', '9.6500', '0', 'Invoiced', 'NWTSO-41', 'Northwind Traders Clam Chowder', '7.2375', '9.6500', '0', 'Soups');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('52', '45', '40', '50.0000', '18.4000', '0', 'Invoiced', 'NWTCM-40', 'Northwind Traders Crab Meat', '13.8000', '18.4000', '0', 'Canned Meat');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('53', '46', '57', '100.0000', '19.5000', '0', 'Invoiced', 'NWTP-57', 'Northwind Traders Ravioli', '14.6250', '19.5000', '0', 'Pasta');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('54', '46', '72', '50.0000', '34.8000', '0', 'Invoiced', 'NWTD-72', 'Northwind Traders Mozzarella', '26.1000', '34.8000', '0', 'Dairy products');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('55', '47', '34', '300.0000', '14.0000', '0', 'Invoiced', 'NWTB-34', 'Northwind Traders Beer', '10.5000', '14.0000', '0', 'Beverages');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('56', '48', '8', '25.0000', '40.0000', '0', 'Invoiced', 'NWTS-8', 'Northwind Traders Curry Sauce', '30.0000', '40.0000', '0', 'Sauces');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('57', '48', '19', '25.0000', '9.2000', '0', 'Invoiced', 'NWTBGM-19', 'Northwind Traders Chocolate Biscuits Mix', '6.9000', '9.2000', '0', 'Baked Goods & Mixes');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('59', '50', '21', '20.0000', '10.0000', '0', 'Invoiced', 'NWTBGM-21', 'Northwind Traders Scones', '7.5000', '10.0000', '0', 'Baked Goods & Mixes');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('60', '51', '5', '25.0000', '21.3500', '0', 'Invoiced', 'NWTO-5', 'Northwind Traders Olive Oil', '16.0125', '21.3500', '0', 'Oil');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('61', '51', '41', '30.0000', '9.6500', '0', 'Invoiced', 'NWTSO-41', 'Northwind Traders Clam Chowder', '7.2375', '9.6500', '0', 'Soups');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('62', '51', '40', '30.0000', '18.4000', '0', 'Invoiced', 'NWTCM-40', 'Northwind Traders Crab Meat', '13.8000', '18.4000', '0', 'Canned Meat');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('66', '56', '48', '10.0000', '12.7500', '0', 'Invoiced', 'NWTCA-48', 'Northwind Traders Chocolate', '9.5625', '12.7500', '0', 'Candy');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('67', '55', '34', '87.0000', '14.0000', '0', 'Invoiced', 'NWTB-34', 'Northwind Traders Beer', '10.5000', '14.0000', '0', 'Beverages');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('68', '79', '7', '30.0000', '30.0000', '0', 'Invoiced', 'NWTDFN-7', 'Northwind Traders Dried Pears', '22.5000', '30.0000', '0', 'Dried Fruit & Nuts');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('69', '79', '51', '30.0000', '53.0000', '0', 'Invoiced', 'NWTDFN-51', 'Northwind Traders Dried Apples', '39.7500', '53.0000', '0', 'Dried Fruit & Nuts');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('70', '78', '17', '40.0000', '39.0000', '0', 'Invoiced', 'NWTCFV-17', 'Northwind Traders Fruit Cocktail', '29.2500', '39.0000', '0', 'Canned Fruit & Vegetables');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('71', '77', '6', '90.0000', '25.0000', '0', 'Invoiced', 'NWTJP-6', 'Northwind Traders Boysenberry Spread', '18.7500', '25.0000', '0', 'Jams, Preserves');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('72', '76', '4', '30.0000', '22.0000', '0', 'Invoiced', 'NWTCO-4', 'Northwind Traders Cajun Seasoning', '16.5000', '22.0000', '0', 'Condiments');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('73', '75', '48', '40.0000', '12.7500', '0', 'Invoiced', 'NWTCA-48', 'Northwind Traders Chocolate', '9.5625', '12.7500', '0', 'Candy');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('74', '74', '48', '40.0000', '12.7500', '0', 'Invoiced', 'NWTCA-48', 'Northwind Traders Chocolate', '9.5625', '12.7500', '0', 'Candy');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('75', '73', '41', '10.0000', '9.6500', '0', 'Invoiced', 'NWTSO-41', 'Northwind Traders Clam Chowder', '7.2375', '9.6500', '0', 'Soups');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('76', '72', '43', '5.0000', '46.0000', '0', 'Invoiced', 'NWTB-43', 'Northwind Traders Coffee', '34.5000', '46.0000', '0', 'Beverages');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('77', '71', '40', '40.0000', '18.4000', '0', 'Invoiced', 'NWTCM-40', 'Northwind Traders Crab Meat', '13.8000', '18.4000', '0', 'Canned Meat');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('78', '70', '8', '20.0000', '40.0000', '0', 'Invoiced', 'NWTS-8', 'Northwind Traders Curry Sauce', '30.0000', '40.0000', '0', 'Sauces');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('79', '69', '80', '15.0000', '3.5000', '0', 'Invoiced', 'NWTDFN-80', 'Northwind Traders Dried Plums', '3.0000', '3.5000', '0', 'Dried Fruit & Nuts');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('80', '67', '74', '20.0000', '10.0000', '0', 'Invoiced', 'NWTDFN-74', 'Northwind Traders Almonds', '7.5000', '10.0000', '0', 'Dried Fruit & Nuts');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('81', '60', '72', '40.0000', '34.8000', '0', 'Invoiced', 'NWTD-72', 'Northwind Traders Mozzarella', '26.1000', '34.8000', '0', 'Dairy products');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('82', '63', '3', '50.0000', '10.0000', '0', 'Invoiced', 'NWTCO-3', 'Northwind Traders Syrup', '7.5000', '10.0000', '0', 'Condiments');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('83', '63', '8', '3.0000', '40.0000', '0', 'Invoiced', 'NWTS-8', 'Northwind Traders Curry Sauce', '30.0000', '40.0000', '0', 'Sauces');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('84', '58', '20', '40.0000', '81.0000', '0', 'Invoiced', 'NWTJP-6', 'Northwind Traders Marmalade', '60.7500', '81.0000', '0', 'Jams, Preserves');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('85', '58', '52', '40.0000', '7.0000', '0', 'Invoiced', 'NWTG-52', 'Northwind Traders Long Grain Rice', '5.2500', '7.0000', '0', 'Grains');
INSERT INTO `order_details` (`id`, `order_id`, `product_id`, `quantity`, `unit_price`, `discount`, `status_name`, `product_code`, `product_name`, `standard_cost`, `list_price`, `discontinued`, `category`) VALUES ('90', '81', '81', '0.0000', '2.9900', '0', 'No Stock', 'NWTB-81', 'Northwind Traders Green Tea', '2.0000', '2.9900', '0', 'Beverages');

-- INSERT INTO `purchase_order_details` (`id`, `purchase_order_id`, `product_id`, `quantity`, `unit_cost`, `date_received`, `posted_to_inventory`, `inventory_id`) VALUES (238, 90, 1, 40, 14, '2006-01-22 00:00:00', 1, 59);

-- INSERT INTO `orders` (`id`, `employee_id`, `customer_id`, `order_date_id`, `shipped_date_id`, `shipper_id`, `ship_name`, `ship_address`, `ship_city`, `ship_state_province`, `ship_zip_postal_code`, `ship_country_region`, `shipping_fee`, `taxes`, `payment_type`, `paid_date`, `notes`, `tax_rate`, `status_id`, `tax_status_name`) VALUES (<{id: }>, <{employee_id: }>, <{customer_id: }>, <{order_date_id: }>, <{shipped_date_id: }>, <{shipper_id: }>, <{ship_name: }>, <{ship_address: }>, <{ship_city: }>, <{ship_state_province: }>, <{ship_zip_postal_code: }>, <{ship_country_region: }>, <{shipping_fee: 0.0000}>, <{taxes: 0.0000}>, <{payment_type: }>, <{paid_date: }>, <{notes: }>, <{tax_rate: 0}>, <{status_id: 0}>, <{tax_status_name: }>);

-- INSERT INTO `date_dimension` (`date_key`, `date`, `day_of_week`, `day_of_month`, `day_name`, `month`, `month_name`, `quarter`, `year`) VALUES (<{date_key: }>, <{date: }>, <{day_of_week: }>, <{day_of_month: }>, <{day_name: }>, <{month: }>, <{month_name: }>, <{quarter: }>, <{year: }>);